global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi'  # Job name for your FastAPI application
    static_configs:
      - targets: ['127.0.0.1:8000']
    metrics_path: '/metrics'  # Path where your FastAPI application exposes metrics (default is '/metrics')
