apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-slave
spec:
  serviceName: "postgres-slave"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-slave
  template:
    metadata:
      labels:
        app: postgres-slave
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:latest
        env:
        - name: POSTGRESQL_REPLICATION_MODE
          value: slave
        - name: POSTGRESQL_MASTER_HOST
          value: postgres-master
        - name: POSTGRESQL_USERNAME
          value: postgres
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRESQL_REPLICATION_USER
          value: replicator
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: replication-password
        volumeMounts:
        - name: pgdata
          mountPath: /bitnami/postgresql
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi
