apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}
spec:
  serviceName: "{{ .Values.appName }}-service"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      monitor: "{{ .Values.monitor }}"
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        monitor: "{{ .Values.monitor }}"
    spec:
      containers:
      - name: postgres
        image: postgres:13.3
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appName }}-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appName }}-secret
              key: password
        - name: POSTGRES_DB
          value: mydatabase
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi
