apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=    # Base64 encoded 'postgres'
  postgres-password: cGFzc3dvcmQ=  # Base64 encoded 'password'
